on:
  push:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug_build:
    name: debug build on push
    uses: ./.github/workflows/android-build.yml
    with:
      build-type: debug
      retention-days: 7
